# Generated by Django 4.0.6 on 2022-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_date_alter_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
